services:
  n8n:
    build: .
    container_name: n8n
    restart: unless-stopped

    environment:
      - TZ=Asia/Jakarta

      - N8N_HOST=n8n.terra-dev.web.id
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.terra-dev.web.id/
      - N8N_EDITOR_BASE_URL=https://n8n.terra-dev.web.id/

      - N8N_ENCRYPTION_KEY=15b7325c206e1386e5153fe5d4687d3e9ab8ba56f1d161f7c6271fc803efc23b

      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123

      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false

      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console

    volumes:
      - n8n_data:/home/node/.n8n

    # ports:
    #   - "5678:5678"

volumes:
  n8n_data:
